name: Bump version
on:
  push:
    branches:
      - master
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: master
          default_bump: patch


      - name: Build Release file
        run: echo ${{ github.sha }} > Release.txt

      - name: Test
        run: cat Release.txt

      # https://github.com/marketplace/actions/gh-release

      - name: Release with GH Release
        uses: softprops/action-gh-release@v1
        with:
          files: Release.txt
          generate_release_notes: true
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: "1 - Release ${{ steps.tag_version.outputs.new_tag }}"
          body: ${{ steps.tag_version.outputs.changelog }}

      # https://github.com/marketplace/actions/create-release
      # https://github.com/ncipollo/release-action

      - name: Release with ncipollo
        uses: ncipollo/release-action@v1
        with:
          #tag: ${{ steps.tag_version.outputs.new_tag }}
          name: "2 - Release ${{ steps.tag_version.outputs.new_tag }}"
          body: ${{ steps.tag_version.outputs.changelog }}
          generateReleaseNotes: true

      # https://github.com/actions/create-release

      - name: Release with base actions
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: "${{ steps.tag_version.outputs.new_tag }}"
          release_name: "3- Release ${{ steps.tag_version.outputs.new_tag }}"
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
          prerelease: true