# name: "tagged-release"

# on:
#   push:
#     tags:
#       - "v*"
# # on:
# #   push:
# #     tags:
# #       - "v*.*.*"

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Build Release file
#         run: echo ${{ github.sha }} > Release.txt

#       - name: Test
#         run: cat Release.txt

#       - name: Set environment variables
#         run: |
#           cat >> $GITHUB_ENV << EOF
#           TAG_VERSION=${GITHUB_REF##*/}
#           EOF

#       # https://github.com/marketplace/actions/gh-release

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         if: startsWith(github.ref, 'refs/tags/')
#         with:
#           files: Release.txt
#           generate_release_notes: true
#           body:

#       # https://github.com/marketplace/actions/create-release

#       - name: Create a GitHub release
#         uses: ncipollo/release-action@v1
#         with:
#           tag: ${{ steps.tag_version.outputs.new_tag }}
#           name: Release ${{ steps.tag_version.outputs.new_tag }}
#           body: ${{ steps.tag_version.outputs.changelog }}
#           generateReleaseNotes: true

#       # https://github.com/actions/create-release

#       - name: Create Release
#         if: ${{ !startsWith(github.ref, 'refs/tags/') }}
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.github_token }}
#         with:
#           tag_name: "${{ steps.tag_version.outputs.new_tag }}"
#           release_name: "${{ steps.tag_version.outputs.new_tag }}"
#           draft: true
#           prerelease: true
